In [13]:
from folktables import ACSDataSource, ACSEmployment
import numpy as np
import pickle
import pandas as pd
import os

In [5]:
data_source = ACSDataSource(survey_year='2019', horizon='1-Year', survey='person')
acs_data = data_source.get_data(download=True)

In [6]:
acs_data

,RT,SERIALNO,DIVISION,SPORDER,PUMA,REGION,ST,ADJINC,PWGTP,AGEP,...,PWGTP71,PWGTP72,PWGTP73,PWGTP74,PWGTP75,PWGTP76,PWGTP77,PWGTP78,PWGTP79,PWGTP80
0,P,2019GQ0000088,6,1,2200,3,1,1010145,11,39,...,22,10,20,13,10,21,12,22,0,10
1,P,2019GQ0000096,6,1,1000,3,1,1010145,70,21,...,67,131,11,10,73,71,128,76,82,69
2,P,2019GQ0000153,6,1,1100,3,1,1010145,20,19,...,20,19,1,43,23,22,1,22,2,21
3,P,2019GQ0000198,6,1,1100,3,1,1010145,79,77,...,156,83,79,76,5,80,159,81,157,82
4,P,2019GQ0000205,6,1,2701,3,1,1010145,53,41,...,8,96,54,98,104,52,53,53,57,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3260721,P,2019HU1412224,0,1,503,9,72,1010145,81,70,...,83,25,31,83,24,22,89,113,57,19
3260722,P,2019HU1412224,0,2,503,9,72,1010145,68,67,...,71,22,22,60,24,24,71,68,58,15
3260723,P,2019HU1412225,0,1,1002,9,72,1010145,68,32,...,19,51,126,93,26,72,74,20,69,20
3260724,P,2019HU1412225,0,2,1002,9,72,1010145,207,27,...,143,167,354,205,68,201,190,60,175,86
3260725,P,2019HU1412225,0,3,1002,9,72,1010145,122,6,...,48,91,173,121,37,122,105,49,138,43

In [16]:
features, label, group = ACSEmployment.df_to_numpy(acs_data)

KeyError: 'RELP'

In [10]:
data_path = '/p/adversarialml/as9rw/datasets/census_new/census_2019_1year'
train_data = pickle.load(open(os.path.join(data_path, "data", 'train.p'), 'rb'))

In [11]:
columns = [
            "age", "workClass", "education-attainment",
            "marital-status", "race", "sex", "cognitive-difficulty",
            "ambulatory-difficulty", "hearing-difficulty", "vision-difficulty",
            "work-hour", "world-area-of-birth", "state-code", "income"
        ]

In [14]:
train_df = pd.DataFrame(train_data, columns=columns)

In [15]:
train_df

,age,workClass,education-attainment,marital-status,race,sex,cognitive-difficulty,ambulatory-difficulty,hearing-difficulty,vision-difficulty,work-hour,world-area-of-birth,state-code,income
0,0.645833,0.000000,0.782609,0.0,1.000000,1.0,0.0,0.0,0.0,0.0,0.404040,0.285714,0.078431,1.0
1,0.364583,0.000000,0.000000,0.0,0.833333,1.0,0.0,0.0,0.0,0.0,0.404040,0.000000,0.039216,0.0
2,0.291667,0.000000,0.956522,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.202020,0.000000,0.235294,0.0
3,0.562500,0.000000,0.652174,0.0,0.166667,1.0,0.0,0.0,0.0,0.0,0.404040,0.000000,0.176471,0.0
4,0.322917,0.000000,0.913043,0.5,0.000000,1.0,0.0,0.0,0.0,0.0,0.404040,0.000000,0.843137,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1129156,0.479167,0.000000,0.782609,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.424242,0.000000,0.647059,1.0
1129157,0.500000,0.000000,0.826087,0.0,0.000000,1.0,0.0,0.0,0.0,0.0,0.404040,0.000000,0.117647,1.0
1129158,0.572917,0.142857,0.347826,0.0,0.000000,1.0,0.0,0.0,0.0,0.0,0.373737,0.285714,0.039216,0.0
1129159,0.197917,0.000000,0.652174,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.505050,0.000000,0.745098,0.0
1129160,0.458333,0.000000,0.782609,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.454545,0.000000,0.431373,1.0

In [17]:
train_df

,age,workClass,education-attainment,marital-status,race,sex,cognitive-difficulty,ambulatory-difficulty,hearing-difficulty,vision-difficulty,work-hour,world-area-of-birth,state-code,income
0,0.645833,0.000000,0.782609,0.0,1.000000,1.0,0.0,0.0,0.0,0.0,0.404040,0.285714,0.078431,1.0
1,0.364583,0.000000,0.000000,0.0,0.833333,1.0,0.0,0.0,0.0,0.0,0.404040,0.000000,0.039216,0.0
2,0.291667,0.000000,0.956522,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.202020,0.000000,0.235294,0.0
3,0.562500,0.000000,0.652174,0.0,0.166667,1.0,0.0,0.0,0.0,0.0,0.404040,0.000000,0.176471,0.0
4,0.322917,0.000000,0.913043,0.5,0.000000,1.0,0.0,0.0,0.0,0.0,0.404040,0.000000,0.843137,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1129156,0.479167,0.000000,0.782609,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.424242,0.000000,0.647059,1.0
1129157,0.500000,0.000000,0.826087,0.0,0.000000,1.0,0.0,0.0,0.0,0.0,0.404040,0.000000,0.117647,1.0
1129158,0.572917,0.142857,0.347826,0.0,0.000000,1.0,0.0,0.0,0.0,0.0,0.373737,0.285714,0.039216,0.0
1129159,0.197917,0.000000,0.652174,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.505050,0.000000,0.745098,0.0
1129160,0.458333,0.000000,0.782609,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.454545,0.000000,0.431373,1.0

In [18]:
def process_df(df):
    def oneHotCatVars(x, colname):
        df_1 = x.drop(columns=colname, axis=1)
        df_2 = pd.get_dummies(x[colname], prefix=colname, prefix_sep=':')
        return (pd.concat([df_1, df_2], axis=1, join='inner'))

    colnames = ['state-code', 'world-area-of-birth',
                'marital-status', 'workClass',
                'education-attainment']
    for colname in colnames:
        df = oneHotCatVars(df, colname)
    return df

In [20]:
processed = process_df(train_df)

In [24]:
levels = train_df['education-attainment'].to_numpy()

In [28]:
things, counts = np.unique(levels, return_counts=True)

In [29]:
counts

array([ 10670,    194,    175,    294,    505,   1117,    754,   1218,
         5689,   1678,   5474,   8410,  12287,  22676,  18283, 231378,
        37913,  81485, 168682, 104234, 255595, 112180,  28637,  19633])

In [40]:
np.sum(counts[20:]) / np.sum(counts)

0.3684549856043558

In [39]:
# Check if any strong correlation exists between the chosen property and task label

0          0.782609
1          0.000000
2          0.956522
3          0.652174
4          0.913043
             ...
1129156    0.782609
1129157    0.826087
1129158    0.347826
1129159    0.652174
1129160    0.782609
Name: education-attainment, Length: 1129161, dtype: float64